#!/usr/bin/env ansible-playbook
---
- name: "Install and configure audio"
  hosts: localhost
  vars:
    configs:
    - pipewire

  tasks:
  - name: "Create symlinks for application configurations"
    ansible.builtin.file:
      src: "{{ playbook_dir }}/config/{{ item }}"
      dest: "{{ ansible_facts['user_dir'] }}/.config/{{ item }}"
      state: link
      owner: "{{ ansible_facts['user_uid'] }}"
      group: "{{ ansible_facts['user_gid'] }}"
    loop: "{{ configs }}"

  - name: "Install Pipewire"
    community.general.pacman:
      name:
      - pipewire # Low-latency audio/video router and processor
      - pipewire-alsa # Low-latency audio/video router and processor - ALSA configuration
      - pipewire-jack # Low-latency audio/video router and processor - JACK replacement
      - pipewire-pulse # Low-latency audio/video router and processor - PulseAudio replacement
      - wiremix # A simple TUI audio mixer for PipeWire
      - wireplumber # Session / policy manager implementation for PipeWire
      state: present
    become: true

  - name: "Install audio production packages"
    community.general.pacman:
      name:
      - ardour # Professional-grade digital audio workstation
      - carla # Audio plugin host
      - lsp-plugins # Collection of open-source plugins
      - noise-repellent # An lv2 plugin for broadband noise reduction
      - x42-plugins # Professional audio processing units available as LV2-plugin and JACK-application
      state: present
    become: true

  - name: "Install audio plugins from AUR"
    kewlfft.aur.aur:
      name:
      - aether.lv2 # An algorithmic reverb based on Cloudseed
      use: "{{ aur_helper }}"
      state: present
    become: true
    become_user: "{{ aur_builder_user }}"

  - name: "Install Bluez"
    community.general.pacman:
      name:
      - bluez # Daemons for the bluetooth protocol stack
      - bluez-utils # Development and debugging utilities for the bluetooth protocol stack
      - bluez-tools # A set of tools to manage Bluetooth devices for Linux
      - bluetui # TUI for managing bluetooth devices
      state: present
    become: true

  - name: "Enable Bluetooth"
    ansible.builtin.systemd:
      name: bluetooth
      state: started
      enabled: true
    become: true
