context.modules = [
  {
    name = libpipewire-module-loopback
    args = {
      node.description = "Rubix44 Main Out 1/2"

      capture.props = {
        node.name = "rubix44_main_out_12"
        node.description = "Rubix44 Main Out 1/2"
        media.class = "Audio/Sink"
        audio.position = [ FL FR ]
        priority.session = 2000
      }

      playback.props = {
        node.name = "playback.rubix44_main_out_12"
        target.object = "alsa_output.usb-Roland_Rubix44-00.pro-output-0"
        audio.position = [ AUX0 AUX1 ]
        stream.dont-remix = true
        node.passive = true
        node.dont-reconnect = true
      }
    }
  }

  {
    name = libpipewire-module-loopback
    args = {
      node.description = "Rubix44 Alt Out 3/4"

      capture.props = {
        node.name = "rubix44_alt_out_34"
        node.description = "Rubix44 Alt Out 3/4"
        media.class = "Audio/Sink"
        audio.position = [ FL FR ]
        priority.session = 1900
      }

      playback.props = {
        node.name = "playback.rubix44_alt_out_34"
        target.object = "alsa_output.usb-Roland_Rubix44-00.pro-output-0"
        audio.position = [ AUX2 AUX3 ]
        stream.dont-remix = true
        node.passive = true
        node.dont-reconnect = true
      }
    }
  }

  {
    name = libpipewire-module-loopback
    args = {
      node.description = "Rubix44 Mic In 1"

      capture.props = {
        node.name = "capture.rubix44_mic_in_1"
        target.object = "alsa_input.usb-Roland_Rubix44-00.pro-input-0"
        audio.position = [ AUX0 ]
        stream.dont-remix = true
        node.passive = true
        node.dont-reconnect = true
      }

      playback.props = {
        node.name = "rubix44_mic_in_1"
        node.description = "Rubix44 Mic In 1"
        media.class = "Audio/Source"
        audio.position = [ MONO ]
        priority.session = 3000
      }
    }
  }
]
