monitor.alsa.rules = [
  {
    matches = [
      { device.name = "alsa_card.pci-0000_01_00.1" }
    ]
    actions = {
      update-props = {
        device.profile = "pro-audio"
      }
    }
  }
  {
    matches = [
      { node.name = "alsa_output.pci-0000_01_00.1.pro-output-9" }
    ]
    actions = {
      update-props = {
        node.description = "ASUS VA27D (HDMI)"
        node.nick = "ASUS VA27D"
      }
    }
  }
  {
    matches = [
      { node.name = "alsa_output.pci-0000_01_00.1.pro-output-11" }
    ]
    actions = {
      update-props = {
        node.description = "AOC U2790PQU (DisplayPort)"
        node.nick = "AOC U2790PQU"
      }
    }
  }
  {
    matches = [
      { node.name = "alsa_output.pci-0000_01_00.1.pro-output-3" }
      { node.name = "alsa_output.pci-0000_01_00.1.pro-output-7" }
      { node.name = "alsa_output.pci-0000_01_00.1.pro-output-8" }
      { node.name = "alsa_output.pci-0000_01_00.1.pro-output-10" }
    ]
    actions = {
      update-props = {
        node.disabled = true
      }
    }
  }
]
